services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80

  app:
    restart: always
    build:
      dockerfile: docker/Docker.Flask
    environment:
      DB_URL: "postgresql://file_user:pswd@postgres/file_database"
      UPLOAD_FOLDER_NAME: "userFiles"
      PATH_SEPARATOR: "/"
      TMP_DIR_NAME: "tmpDir"
    volumes:
      - ./userFiles:/app/userFiles
      - ./src:/app/src
#    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "file_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ps"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    name: test
