services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80

  minio:
    image: docker.io/bitnami/minio:2022
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/minio/data/:/data

  app-sync:
    build:
      dockerfile: Dockerfile
    environment:
      MODE: ${MODE}
      MINIO_URL: ${MINIO_URL}
      DEFAULT_BUCKET_NAME: ${DEFAULT_BUCKET_NAME}
      DB_URL: ${DB_URL}
      UPLOAD_FOLDER_NAME: ${UPLOAD_FOLDER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      PATH_SEPARATOR: ${PATH_SEPARATOR}
    volumes:
      - ./docker/minio/credentials:/root/.aws/credentials
      - ./docker/cron/logs/:/logs/
      - ./docker/file_storage:/file_storage
      - ./src:/app/src
    command: crond -f -d 8

  app:
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      MODE: ${MODE}
      MINIO_URL: ${MINIO_URL}
      DEFAULT_BUCKET_NAME: ${DEFAULT_BUCKET_NAME}
      DB_URL: ${DB_URL}
      UPLOAD_FOLDER_NAME: ${UPLOAD_FOLDER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      PATH_SEPARATOR: ${PATH_SEPARATOR}
      MAX_CONTENT_LENGTH: ${MAX_CONTENT_LENGTH}
    volumes:
      - ./docker/file_storage:/file_storage
      - ./src:/app/src
    command: gunicorn --bind 0.0.0.0:5000 --pythonpath src main:app

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - ${DATABASE_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    name: test
