services:
  web_server:
    restart: always
    container_name: nginx
    build:
      dockerfile: Nginx
    ports:
      - 80:80
    depends_on:
      - app
    links:
      - app

  app:
    restart: always
    container_name: flask
    build:
      dockerfile: Flask
    environment:
      DB_URL: "postgresql://file_user:pswd@database/file_database"
      SEPARATOR: '/'
      UPLOAD_DIR_NAME: 'userFiles'
    ports:
      - 5000:5000
    depends_on:
      - database
    links:
      - database

  database:
    restart: always
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "file_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ps"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432