services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80

  minio:
    image: docker.io/bitnami/minio:2022
    environment:
      MINIO_ROOT_USER: "minio-user"
      MINIO_ROOT_PASSWORD: "minio-password"
    volumes:
      - ./docker/minio/data/:/data

  app-sync:
    build:
      dockerfile: Dockerfile
    environment:
      MODE: 'MINIO'
      MINIO_URL: 'http://minio:9000'
      DEFAULT_BUCKET_NAME: 'default'
      DB_URL: "postgresql://file_user:pswd@postgres/file_database"
      UPLOAD_FOLDER_NAME: "user_files"
      ROOT_DIR: '/file_storage'
      PATH_SEPARATOR: "/"
    volumes:
      - ./docker/minio/credentials:/root/.aws/credentials
      - ./docker/cron/logs/:/logs/
      - ./docker/file_storage:/file_storage
      - ./src:/app/src
    command: crond -f -d 8

  app:
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      MODE: 'MINIO'
      MINIO_URL: 'http://minio:9000'
      DEFAULT_BUCKET_NAME: 'default'
      DB_URL: "postgresql://file_user:pswd@postgres/file_database"
      UPLOAD_FOLDER_NAME: "user_files"
      ROOT_DIR: '/file_storage'
      PATH_SEPARATOR: "/"
      MAX_CONTENT_LENGTH: 6M
    volumes:
      - ./docker/file_storage:/file_storage
      - ./src:/app/src
    command: gunicorn --bind 0.0.0.0:5000 --pythonpath src main:app

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "file_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ps"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    name: test
