services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80

  app-sync:
    build:
      dockerfile: Dockerfile
    environment:
      DB_URL: "postgresql://file_user:pswd@postgres/file_database"
      UPLOAD_FOLDER_NAME: "user_files"
      TMP_FOLDER_NAME: "tmp_dir"
      ROOT_DIR: '/file_storage'
      PATH_SEPARATOR: "/"
    volumes:
      - ./docker/cron/logs/output.log:/logs/output.log
      - ./docker/cron/logs/err.log:/logs/err.log
      - ./docker/file_storage:/file_storage
      - ./src:/app/src
    command: crond -f -d 8

  app:
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      DB_URL: "postgresql://file_user:pswd@postgres/file_database"
      UPLOAD_FOLDER_NAME: "user_files"
      TMP_FOLDER_NAME: "tmp_dir"
      ROOT_DIR: '/file_storage'
      PATH_SEPARATOR: "/"
      MAX_CONTENT_LENGTH: 6M
    volumes:
      - ./docker/file_storage:/file_storage
      - ./src:/app/src
    command: gunicorn --bind 0.0.0.0:5000 --pythonpath src main:app

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "file_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ps"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    name: test
